language: go

go:
  - 1.8

install: true

notifications:
  email: false

before_script:
  - echo ${TRAVIS_BUILD_DIR}
  - pwd && ls -la
  - export GOPATH="${TRAVIS_BUILD_DIR}/vendor:${TRAVIS_BUILD_DIR}"
  - env
  - go get -v -t -d ./src/...

script:
  - go test -v -cover ./src/...
  - go build -v -i -x --ldflags '-extldflags "-static"' -o bin/core src/main.go


