language: go

go:
  - 1.8

#before_install:
#  - go get github.com/mattn/goveralls
#  - go get -u github.com/golang/dep/cmd/dep
#  - dep ensure


install: true

notifications:
  email: false

before_script:
  - export GOPATH="${TRAVIS_BUILD_DIR}/vendor:${TRAVIS_BUILD_DIR}"
  - export IMAGE_NAME='idconstruct/consul-service-validator'
  - export SOURCE_IMAGE='alpine'
  - env
  - go get -v -t -d ./src/...


script:
  - go test -v -cover ./src/...
  - go build -i --ldflags '-extldflags "-static"' -o bin/core src/main.go
  - packer validate packer/docker.json
  - packer build packer/docker.json


