language: go

go:
  - 1.8

#before_install:
#  - go get github.com/mattn/goveralls
#  - go get -u github.com/golang/dep/cmd/dep
#  - dep ensure

install: true

notifications:
  email: false

jobs:
  include:
    - stage: test
      script:
      - export GOPATH="${TRAVIS_BUILD_DIR}/vendor:${TRAVIS_BUILD_DIR}"
      - go get -v -t -d ./src/...
      - go test -v -cover ./src/...
    - stage: build docker image
      script:
      - export SOURCE_IMAGE='alpine'
      - export PROJECT_NAME='consul-service-validator'
      - export GOPATH="${TRAVIS_BUILD_DIR}/vendor:${TRAVIS_BUILD_DIR}"
      - export IMAGE_NAME=$DOCKER_USERNAME/$PROJECT_NAME
      - env
      - go get -v -t -d ./src/...
      - go build -i -v --ldflags '-extldflags "-static"' -o bin/validator src/main.go
      - docker login -u="$DOCKER_USERNAME" -p="$DOCKER_PASSWORD"
      - docker build -t $IMAGE_NAME .
      - docker images
      - docker tag $IMAGE_NAME $IMAGE_NAME
      - docker push $IMAGE_NAME




