language: go

go:
  - 1.8


before_script:
  - GO_FILES=$(find . -iname '*.go' -type f | grep -v /vendor/) # All the .go files, excluding vendor/
  - go get -v -t -d ./src/...

script:
  - go test -v -cover ./src/...
  - go build -v -i -x --ldflags '-extldflags "-static"' -o bin/core src/main.go
